/* design-sync prepare step — everything the converter needs that the app's own
   build doesn't produce. Run from the repo root; idempotent.

   1. Compile Tailwind to a stable path. The app's dist CSS is content-hashed
      (index-<hash>.css), so it can't be named in config; this also widens the
      output with the token safelist (see tailwind.ds.config.mjs).
   2. Emit .d.ts. Without them the converter falls back to a
      `[key: string]: unknown` stub and every component ships an empty API
      contract to the design agent.
   3. Write the barrel the converter's export scan reads (package.json "types"
      points at it). Scoped to components/ — routes and lib are not design
      system surface. */
import { execFileSync } from 'node:child_process';
import { readdirSync, writeFileSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

const FE = 'frontend';
// shell:true is required on Windows � Node refuses to spawnSync a .cmd
// shim directly (EINVAL) since the 18.20/20.12 argument-injection fix.
const run = (args) =>
  execFileSync('npx', args, { cwd: FE, stdio: 'inherit', shell: true });

run(['tailwindcss', '-c', '../.design-sync/tailwind.ds.config.mjs',
     '-i', './src/styles/tokens.css', '-o', './.ds-css/ds.css']);
run(['tsc', '-p', 'tsconfig.ds.json']);

const typesRoot = join(FE, '.ds-types');
const walk = (d) => readdirSync(d).flatMap((n) => {
  const p = join(d, n);
  return statSync(p).isDirectory() ? walk(p) : p.endsWith('.d.ts') ? [p] : [];
});
const specs = walk(join(typesRoot, 'components'))
  .map((p) => './' + relative(typesRoot, p).split(sep).join('/').replace(/[.]d[.]ts$/, ''))
  .sort();
writeFileSync(join(typesRoot, 'index.d.ts'),
  '/* Generated by .design-sync/prepare.mjs — do not edit. */\n' +
  specs.map((s) => `export * from ${JSON.stringify(s)};`).join('\n') + '\n');
console.error(`prepare: ${specs.length} component declarations -> ${typesRoot}/index.d.ts`);
